- name: Task Var
  hosts: local
  vars: 
   - Course: "DevOps with AWS"
   - Trainer: "Asif"
   - Duration: "120Hrs"
  tasks: 
  - name: task variable
    vars: 
    - Course: "Ansible"
    ansible.builtin.debug:
    msg: "Course is {{Course}},Trainer is {{Trainer}},Duration is {{Duration}}"

    
