- name: Conditions
  hosts: local
  vars:
   my_number: 100
  tasks:
  - name: Print if number is Greater than 10
    ansible.builtin.debug:
     msg: "number {{My_Number}} is graeter than 10"
    when: My_Number > 10

  - name: Print if number is less than 10
    ansible.builtin.debug:
     msg: "number {{My_Number}} is less than 10"
    when: My_Number <= 10

