- name: install nginx in RHEL and Ubuntu 
  hosts: local
  become: yes
  tasks: 
  - name: Install nginx if RHEL
    ansible.builtin.dnf:
      name: nginx
      state: present
    when: ansible_os_family == "Redhat"  

  - name: Install nginx if Ubuntu
    ansible.builtin.apt:
      name: nginx
      state: present
    when: ansible_os_family == "Debian"  