- name: Install Multiple Packages
  hosts: local
  become: yes
  tasks:
  - name: Install Packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
    - mysql
    - gcc
   