- name: install and remove packages
  hosts: local
  become: yes
  tasks:
  - name: install and remove
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - {name: 'mysql' state: 'absent'}
    - {name: 'gcc' state: 'absent'}
    - {name: 'zip' state: 'present'}
  