- name: Filters
  hosts: local
  tasks: 
   - name: handle undifined case
     ansible.builtin.debug:
      msg: "Hello {{ person | default('Adam')}}"

   - name: convert string to list
     vars:
      Fruits: "Apple, Banana, Orange"
     ansible.builtin.debug:
      msg: "Fruits are: {{Fruits | split(',')}}"

   - name: Converting Map to list
     vars:
      Course:
       name: DevOps
       duration: 120hrs
       trainer: Asif
     ansible.builtin.debug:
      msg: "Course info :: {{ Course | dict2items }}"


      - name: Converting List to Map
     vars:
      Course:
        - {'key': 'name', 'value': 'DevOps'}
        - {'key': 'duration', 'value': '120hrs'}
        - {'key': 'trainer', 'value': 'Asif'}
       
     ansible.builtin.debug:
      msg: "Course info :: {{ Course | items2dict }}"


     